/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiConversationsRouteImport } from './routes/api/conversations'
import { Route as ApiCheckpointsRouteImport } from './routes/api/checkpoints'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiOpenrouterValidateRouteImport } from './routes/api/openrouter/validate'
import { Route as ApiConversationsIdRouteImport } from './routes/api/conversations/$id'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsRoute = ApiConversationsRouteImport.update({
  id: '/api/conversations',
  path: '/api/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckpointsRoute = ApiCheckpointsRouteImport.update({
  id: '/api/checkpoints',
  path: '/api/checkpoints',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenrouterValidateRoute = ApiOpenrouterValidateRouteImport.update({
  id: '/api/openrouter/validate',
  path: '/api/openrouter/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsIdRoute = ApiConversationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiConversationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/chat': typeof ApiChatRoute
  '/api/checkpoints': typeof ApiCheckpointsRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/conversations/$id': typeof ApiConversationsIdRoute
  '/api/openrouter/validate': typeof ApiOpenrouterValidateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/chat': typeof ApiChatRoute
  '/api/checkpoints': typeof ApiCheckpointsRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/conversations/$id': typeof ApiConversationsIdRoute
  '/api/openrouter/validate': typeof ApiOpenrouterValidateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/chat': typeof ApiChatRoute
  '/api/checkpoints': typeof ApiCheckpointsRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/conversations/$id': typeof ApiConversationsIdRoute
  '/api/openrouter/validate': typeof ApiOpenrouterValidateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/api/chat'
    | '/api/checkpoints'
    | '/api/conversations'
    | '/api/conversations/$id'
    | '/api/openrouter/validate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/api/chat'
    | '/api/checkpoints'
    | '/api/conversations'
    | '/api/conversations/$id'
    | '/api/openrouter/validate'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/api/chat'
    | '/api/checkpoints'
    | '/api/conversations'
    | '/api/conversations/$id'
    | '/api/openrouter/validate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCheckpointsRoute: typeof ApiCheckpointsRoute
  ApiConversationsRoute: typeof ApiConversationsRouteWithChildren
  ApiOpenrouterValidateRoute: typeof ApiOpenrouterValidateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations': {
      id: '/api/conversations'
      path: '/api/conversations'
      fullPath: '/api/conversations'
      preLoaderRoute: typeof ApiConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkpoints': {
      id: '/api/checkpoints'
      path: '/api/checkpoints'
      fullPath: '/api/checkpoints'
      preLoaderRoute: typeof ApiCheckpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openrouter/validate': {
      id: '/api/openrouter/validate'
      path: '/api/openrouter/validate'
      fullPath: '/api/openrouter/validate'
      preLoaderRoute: typeof ApiOpenrouterValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$id': {
      id: '/api/conversations/$id'
      path: '/$id'
      fullPath: '/api/conversations/$id'
      preLoaderRoute: typeof ApiConversationsIdRouteImport
      parentRoute: typeof ApiConversationsRoute
    }
  }
}

interface ApiConversationsRouteChildren {
  ApiConversationsIdRoute: typeof ApiConversationsIdRoute
}

const ApiConversationsRouteChildren: ApiConversationsRouteChildren = {
  ApiConversationsIdRoute: ApiConversationsIdRoute,
}

const ApiConversationsRouteWithChildren =
  ApiConversationsRoute._addFileChildren(ApiConversationsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCheckpointsRoute: ApiCheckpointsRoute,
  ApiConversationsRoute: ApiConversationsRouteWithChildren,
  ApiOpenrouterValidateRoute: ApiOpenrouterValidateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
